import type { Plugin } from "./types.js";

/**
 * Plugin metadata list.
 * File copying is handled via the shadcn registry.
 * This array is used for list, info and post-install messages.
 */
export const PLUGINS: Plugin[] = [
  {
    name: "i18n",
    title: "Internationalization (Paraglide)",
    description: "Compile-time i18n with inlang Paraglide. TR/EN language support",
    packages: ["@inlang/paraglide-js", "@inlang/paraglide-vite"],
    registryDependencies: ["@tra-kit/language-select"],
    postInstall: [
      "",
      "📦 i18n (Paraglide) installed!",
      "",
      "📌 Next steps:",
      "  1. Add Paraglide plugin to vite.config.ts:",
      "",
      '     import { paraglideVitePlugin } from "@inlang/paraglide-js"',
      "",
      "     plugins: [",
      '       paraglideVitePlugin({ project: "./src/project.inlang", outdir: "./src/paraglide" })',
      "     ]",
      "",
      "  2. Run npm run dev once — this generates src/paraglide/ folder",
      "  3. Add your translation keys to messages/tr.json and messages/en.json",
      "",
      "  Usage in components:",
      "",
      '     import { useM } from "@/lib/locale"',
      "",
      "     const m = useM()",
      "",
      '     <p>{m.hello({ name: "Test" })}</p>',
      "",
      "  ⚠️  src/paraglide/ folder is auto-generated. Do not edit it manually.",
    ],
  },
  {
    name: "axios",
    title: "HTTP Client (Axios)",
    description:
      "Axios instance, interceptors, token management, AuthContext/AuthProvider and createService pattern",
    packages: ["axios"],
    registryDependencies: [],
    postInstall: [
      "",
      "📦 HTTP Client (Axios) installed!",
      "",
      "📌 Next steps:",
      "  1. Edit src/constants/ApiEnvironment.ts with your API base URLs",
      "  2. Wrap your app with <AuthProvider> in main.tsx",
      "  3. Use createService() to create your API services:",
      "",
      '     import { createService } from "@/services/BaseService"',
      '     const UserService = createService("User/", (s) => ({',
      '       login: (data: LoginRequest) => s.post("Login", data),',
      '       list: () => s.get("List"),',
      "     }));",
      "",
      "  ℹ️  401 responses automatically trigger logout via AuthContext.",
    ],
  },
  {
    name: "signalr",
    title: "Real-time (SignalR)",
    description:
      "SignalR HubConnection management, auto-reconnect, MessageHubContext, useSignalR hooks",
    packages: ["@microsoft/signalr"],
    registryDependencies: [],
    postInstall: [
      "",
      "📦 SignalR installed!",
      "",
      "📌 Next steps:",
      "  1. Update HUB_URL in src/lib/signalr.ts",
      "  2. Wrap your app with MessageHubProvider in main.tsx (inside AuthProvider)",
      "  3. Use the useMessageHub hook in your components",
    ],
  },
  {
    name: "table",
    title: "Data Table (TanStack Table)",
    description:
      "TanStack Table wrapper with sorting, filtering, pagination, export and skeleton support",
    packages: ["@tanstack/react-table"],
    registryDependencies: ["@tra-kit/skeleton", "@tra-kit/input"],
    postInstall: [
      "",
      "📦 Data Table (TanStack Table) installed!",
      "",
      "📌 Next steps:",
      "  1. Gerekli importları ekleyin:",
      '     import { useMemo } from "react"',
      '     import type { ColumnDef } from "@tanstack/react-table"',
      '     import CustomTable from "@/components/table/custom-table"',
      "",
      "  2. Kolon tipinizi belirleyin (örnek):",
      "     type User = { id: number; name: string }",
      "",
      "  3. Kolonları ve veriyi tanımlayın:",
      "     const columns = useMemo<ColumnDef<User>[]>(() => [",
      '       { header: "ID", accessorKey: "id" },',
      '       { header: "Name", accessorKey: "name" },',
      "     ], [])",
      "     const data = Array.from({ length: 20 }, (_, i) => ({ id: i + 1, name: `User ${i + 1}` }))",
      "",
      "  4. Tabloyu kullanın:",
      "     <CustomTable columns={columns} data={data} />",
      "",
      "  ⚠️  Not: columns dizisinin type'ı örnekte 'User' olarak tanımlandı. Kendi veri modelinize göre değiştirin.",
    ],
  },
  {
    name: "forms",
    title: "Form Management (Formik + Yup)",
    description:
      "Formik + Yup integration, TRA UI Kit-bound form components and shared Validations constants",
    packages: ["formik", "yup"],
    registryDependencies: [
      "@tra-kit/text-field",
      "@tra-kit/select",
      "@tra-kit/checkbox",
      "@tra-kit/date-picker",
      "@tra-kit/radio-buttons",
      "@tra-kit/label",
    ],
    postInstall: [
      "",
      "📦 Form Management (Formik + Yup) installed!",
      "",
      "📌 Usage:",
      '  import { FormikTextField, FormikSelect } from "@/components/formik"',
      "",
      "  Validation schemas: src/constants/Validations.ts",
    ],
  },
];
